### ISSUE TITLE
browserify issue

### ISSUE THREAD

**Issue by workmaps** [christippett/leaflet-material#2]
Greetings, how do you have any instructions on how to get this up and running with browserify? I'm getting a "Uncaught (in promise) Error: Invalid argument: L.mapbox.gridLayer expected(…)" error. Any suggestions will be much appreciated. 
Thanks

**Comment by workmaps** [comment]
I had to globalize leaflet, and require the libraries just so in coffeescript:
require 'mapbox.js'
materialControl = require 'leaflet-material-controls'
global.L = require 'leaflet'

I also had to drop the L when creating a new control:

```
materialZoomControl = new (materialControl.Zoom)(
  position: 'topright'
  materialOptions: materialOptions).addTo(@map)
```

Great plugin! Thanks for sharing!

workmaps

**Comment by christippett** [comment]
@workmaps, apologies for not responding before now. Thanks for adding the comment with how you got it working with Browserify. When I have a spare moment I'll look at improving the instructions in the README.
