### ISSUE TITLE
ZoomControl zoom out defaults to +

### ISSUE THREAD

**Issue by CookieMuffin** [christippett/leaflet-material#6]
Hi,

I am trying out this library using the npm repository.  It is slightly outdated (doesn't have the patch so that mapbox isn't required), but otherwise works fine.  What I noticed when using the default zoom control, is that both the zoom in button and zoom out button use the + icon.
`    const materialZoomControl = new L.materialControl.Zoom({
      position: 'topright',
    });`
If I use the option zoomOutText: '-', it works fine.

Would it be possible to add '-' to the default behaviour?

**Comment by christippett** [comment]
Hey @CookieMuffin, thanks for picking this up. You're absolutely right, by default this should show "-" for the zoom out control. I'll put through a fix for this ASAP.
